"""initial

Revision ID: af6c4e767923
Revises: 
Create Date: 2026-04-30 23:30:23.979164+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'af6c4e767923'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_log',
    sa.Column('principal_id', sa.UUID(), nullable=True),
    sa.Column('principal_email', sa.String(length=320), nullable=True),
    sa.Column('person_uid', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource', sa.String(length=128), nullable=True),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_log')),
    schema='audit'
    )
    op.create_index('ix_access_log_action', 'access_log', ['action'], unique=False, schema='audit')
    op.create_index('ix_access_log_person_uid', 'access_log', ['person_uid'], unique=False, schema='audit')
    op.create_index('ix_access_log_principal_id', 'access_log', ['principal_id'], unique=False, schema='audit')
    op.create_table('person',
    sa.Column('given_name', sa.String(length=120), nullable=True),
    sa.Column('family_name', sa.String(length=120), nullable=True),
    sa.Column('display_name', sa.String(length=240), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person')),
    schema='identity'
    )
    op.create_table('raw_event',
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_event')),
    schema='ingest'
    )
    op.create_index('ix_raw_event_external_id', 'raw_event', ['external_id'], unique=False, schema='ingest')
    op.create_index('ix_raw_event_received_at', 'raw_event', ['received_at'], unique=False, schema='ingest')
    op.create_index('ix_raw_event_source', 'raw_event', ['source'], unique=False, schema='ingest')
    op.create_table('followup_task',
    sa.Column('person_uid', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_followup_task')),
    schema='ops'
    )
    op.create_index('ix_followup_task_due_at', 'followup_task', ['due_at'], unique=False, schema='ops')
    op.create_index('ix_followup_task_person_uid', 'followup_task', ['person_uid'], unique=False, schema='ops')
    op.create_table('lead',
    sa.Column('person_uid', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead')),
    schema='ops'
    )
    op.create_index('ix_lead_person_uid', 'lead', ['person_uid'], unique=False, schema='ops')
    op.create_table('consultation',
    sa.Column('person_uid', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('clinician_uid', sa.UUID(), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultation')),
    schema='phi'
    )
    op.create_index('ix_consultation_occurred_at', 'consultation', ['occurred_at'], unique=False, schema='phi')
    op.create_index('ix_consultation_person_uid', 'consultation', ['person_uid'], unique=False, schema='phi')
    op.create_table('patient_profile',
    sa.Column('person_uid', sa.UUID(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex_at_birth', sa.String(length=16), nullable=True),
    sa.Column('allergies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('medical_history', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_profile')),
    schema='phi'
    )
    op.create_index('ix_patient_profile_person_uid', 'patient_profile', ['person_uid'], unique=True, schema='phi')
    op.create_table('person_identifier',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=320), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['identity.person.id'], name=op.f('fk_person_identifier_person_id_person'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person_identifier')),
    sa.UniqueConstraint('kind', 'value', name='uq_person_identifier_kind_value'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_person_identifier_person_id'), 'person_identifier', ['person_id'], unique=False, schema='identity')
    op.create_index('ix_person_identifier_value', 'person_identifier', ['value'], unique=False, schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_person_identifier_value', table_name='person_identifier', schema='identity')
    op.drop_index(op.f('ix_identity_person_identifier_person_id'), table_name='person_identifier', schema='identity')
    op.drop_table('person_identifier', schema='identity')
    op.drop_index('ix_patient_profile_person_uid', table_name='patient_profile', schema='phi')
    op.drop_table('patient_profile', schema='phi')
    op.drop_index('ix_consultation_person_uid', table_name='consultation', schema='phi')
    op.drop_index('ix_consultation_occurred_at', table_name='consultation', schema='phi')
    op.drop_table('consultation', schema='phi')
    op.drop_index('ix_lead_person_uid', table_name='lead', schema='ops')
    op.drop_table('lead', schema='ops')
    op.drop_index('ix_followup_task_person_uid', table_name='followup_task', schema='ops')
    op.drop_index('ix_followup_task_due_at', table_name='followup_task', schema='ops')
    op.drop_table('followup_task', schema='ops')
    op.drop_index('ix_raw_event_source', table_name='raw_event', schema='ingest')
    op.drop_index('ix_raw_event_received_at', table_name='raw_event', schema='ingest')
    op.drop_index('ix_raw_event_external_id', table_name='raw_event', schema='ingest')
    op.drop_table('raw_event', schema='ingest')
    op.drop_table('person', schema='identity')
    op.drop_index('ix_access_log_principal_id', table_name='access_log', schema='audit')
    op.drop_index('ix_access_log_person_uid', table_name='access_log', schema='audit')
    op.drop_index('ix_access_log_action', table_name='access_log', schema='audit')
    op.drop_table('access_log', schema='audit')
    # ### end Alembic commands ###
